# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loex < Formula
  desc "Loex: Local Execution Manager CLI"
  homepage "https://github.com/kjunh972/loex"
  version "1.1.0"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    on_intel do
      url "https://github.com/kjunh972/loex/releases/download/v1.1.0/loex-1.1.0-darwin-amd64.tar.gz"
      sha256 "c9a9de9335c1680403d2e0d615d71e2a54bd39bf42dd4ecd1b77fbdb42a97af9"

      def install
        bin.install "loex"

        # Install shell completions
        generate_completions_from_executable(bin/"loex", "completion")
      end
    end
    on_arm do
      url "https://github.com/kjunh972/loex/releases/download/v1.1.0/loex-1.1.0-darwin-arm64.tar.gz"
      sha256 "c7684bad13f45515cf9aaa354867b997521ba940b5c4b39f5386a3a42bc03573"

      def install
        bin.install "loex"

        # Install shell completions
        generate_completions_from_executable(bin/"loex", "completion")
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kjunh972/loex/releases/download/v1.1.0/loex-1.1.0-linux-amd64.tar.gz"
        sha256 "592fd13199c6f53296ebc440c146b395ff058a185c30d49335b31574962a69f5"

        def install
          bin.install "loex"

          # Install shell completions
          generate_completions_from_executable(bin/"loex", "completion")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kjunh972/loex/releases/download/v1.1.0/loex-1.1.0-linux-arm64.tar.gz"
        sha256 "57cd1feb36b85bd31bacafc78e020cd956dfd500f3ff08dff487634d39fb0178"

        def install
          bin.install "loex"

          # Install shell completions
          generate_completions_from_executable(bin/"loex", "completion")
        end
      end
    end
  end

  def caveats
    <<~EOS
      Get started with Loex:
        loex init myproject
        loex config wizard myproject
        loex start myproject

      For more information, run: loex --help
    EOS
  end

  test do
    system "#{bin}/loex", "--version"
    system "#{bin}/loex", "--help"
  end
end
