# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loex < Formula
  desc "Loex: Local Execution Manager CLI"
  homepage "https://github.com/kjunh972/loex"
  version "1.0.0"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    on_intel do
      url "https://github.com/kjunh972/loex/releases/download/v1.0.0/loex-1.0.0-darwin-amd64.tar.gz"
      sha256 "26d8858c853c5785c881109e8b7a058e031c270d6ef3885366ce6896da208e00"

      def install
        bin.install "loex"

        # Install shell completions
        generate_completions_from_executable(bin/"loex", "completion")
      end
    end
    on_arm do
      url "https://github.com/kjunh972/loex/releases/download/v1.0.0/loex-1.0.0-darwin-arm64.tar.gz"
      sha256 "c43bb239063b7c384430bb9e307d55e92f061bc26a15605cf8142f7058384669"

      def install
        bin.install "loex"

        # Install shell completions
        generate_completions_from_executable(bin/"loex", "completion")
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kjunh972/loex/releases/download/v1.0.0/loex-1.0.0-linux-amd64.tar.gz"
        sha256 "fd3693ad3770a9d43fde3b6bdffc1bdaee5dc2286f82a7bbe1879e76058e8cca"

        def install
          bin.install "loex"

          # Install shell completions
          generate_completions_from_executable(bin/"loex", "completion")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kjunh972/loex/releases/download/v1.0.0/loex-1.0.0-linux-arm64.tar.gz"
        sha256 "89cfa0aa5cc0c836921ad6d901bbfc942b397d1dfa314f3b486356f64b22fd9c"

        def install
          bin.install "loex"

          # Install shell completions
          generate_completions_from_executable(bin/"loex", "completion")
        end
      end
    end
  end

  def caveats
    <<~EOS
      Get started with Loex:
        loex init myproject
        loex config wizard myproject
        loex start myproject

      For more information, run: loex --help
    EOS
  end

  test do
    system "#{bin}/loex", "--version"
    system "#{bin}/loex", "--help"
  end
end
